# Generated by Django 4.2.4 on 2023-08-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_category_options_alter_resources_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resources',
            name='rate',
        ),
    ]
